# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ColorMVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'RxViewBinder', '~> 2.0.0'
    pod 'RxDataSources', '~> 4.0'
  # Pods for ColorMVVM

end
